/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartBox: typeof import('./src/components/dataService/chart/ChartBox.vue')['default']
    ConditionBox: typeof import('./src/components/dataService/condition/ConditionBox.vue')['default']
    copy: typeof import('./src/components/dataService/Map2D copy.vue')['default']
    DataService: typeof import('./src/components/dataService/DataService.vue')['default']
    'DataService copy': typeof import('./src/components/dataService/DataService copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    HomeBody: typeof import('./src/components/home/HomeBody.vue')['default']
    Legend: typeof import('./src/components/dataService/common/Legend.vue')['default']
    Map2D: typeof import('./src/components/dataService/Map2D.vue')['default']
    'Map2D copy': typeof import('./src/components/dataService/Map2D copy.vue')['default']
    Map3D: typeof import('./src/components/dataService/Map3D.vue')['default']
    MapInfo: typeof import('./src/components/dataService/common/MapInfo.vue')['default']
    NavPage: typeof import('./src/components/home/nav-page.vue')['default']
    NavPage1: typeof import('./src/components/home/nav-page1.vue')['default']
    NavPage2: typeof import('./src/components/home/nav-page2.vue')['default']
    NavPage3: typeof import('./src/components/home/nav-page3.vue')['default']
    Paper1: typeof import('./src/components/home/theme1/paper1.vue')['default']
    Paper2: typeof import('./src/components/home/theme1/paper2.vue')['default']
    Paper3: typeof import('./src/components/home/theme1/paper3.vue')['default']
    Paper4: typeof import('./src/components/home/theme1/paper4.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableBox: typeof import('./src/components/dataService/chart/table/TableBox.vue')['default']
    Theme: typeof import('./src/components/home/theme.vue')['default']
    ThemeDistribute: typeof import('./src/components/home/themeDistribute.vue')['default']
    ToolBox: typeof import('./src/components/dataService/chart/table/ToolBox.vue')['default']
  }
}
